// Code generated by MockGen. DO NOT EDIT.
// Source: startup.go

// Package mock_startup is a generated GoMock package.
package mock_startup

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	api "github.com/openshift/openshift-azure/pkg/api"
	keyvault "github.com/openshift/openshift-azure/pkg/util/azureclient/keyvault"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// WriteFiles mocks base method
func (m *MockInterface) WriteFiles(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFiles", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFiles indicates an expected call of WriteFiles
func (mr *MockInterfaceMockRecorder) WriteFiles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFiles", reflect.TypeOf((*MockInterface)(nil).WriteFiles), ctx)
}

// WriteFilesExt mocks base method
func (m *MockInterface) WriteFilesExt(ctx context.Context, kvc keyvault.KeyVaultClient, hostname, domainname, dirPrefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFilesExt", ctx, kvc, hostname, domainname, dirPrefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFilesExt indicates an expected call of WriteFilesExt
func (mr *MockInterfaceMockRecorder) WriteFilesExt(ctx, kvc, hostname, domainname, dirPrefix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFilesExt", reflect.TypeOf((*MockInterface)(nil).WriteFilesExt), ctx, kvc, hostname, domainname, dirPrefix)
}

// Hash mocks base method
func (m *MockInterface) Hash(role api.AgentPoolProfileRole) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", role)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash
func (mr *MockInterfaceMockRecorder) Hash(role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockInterface)(nil).Hash), role)
}
