// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/openshift-azure/pkg/util/azureclient/operationalinsights (interfaces: WorkspacesClient)

// Package mock_operationalinsights is a generated GoMock package.
package mock_operationalinsights

import (
	context "context"
	reflect "reflect"

	operationalinsights "github.com/Azure/azure-sdk-for-go/services/preview/operationalinsights/mgmt/2015-11-01-preview/operationalinsights"
	gomock "github.com/golang/mock/gomock"
)

// MockWorkspacesClient is a mock of WorkspacesClient interface
type MockWorkspacesClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspacesClientMockRecorder
}

// MockWorkspacesClientMockRecorder is the mock recorder for MockWorkspacesClient
type MockWorkspacesClientMockRecorder struct {
	mock *MockWorkspacesClient
}

// NewMockWorkspacesClient creates a new mock instance
func NewMockWorkspacesClient(ctrl *gomock.Controller) *MockWorkspacesClient {
	mock := &MockWorkspacesClient{ctrl: ctrl}
	mock.recorder = &MockWorkspacesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorkspacesClient) EXPECT() *MockWorkspacesClientMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method
func (m *MockWorkspacesClient) CreateOrUpdate(arg0 context.Context, arg1, arg2 string, arg3 operationalinsights.Workspace) (operationalinsights.WorkspacesCreateOrUpdateFuture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(operationalinsights.WorkspacesCreateOrUpdateFuture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate
func (mr *MockWorkspacesClientMockRecorder) CreateOrUpdate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockWorkspacesClient)(nil).CreateOrUpdate), arg0, arg1, arg2, arg3)
}

// Get mocks base method
func (m *MockWorkspacesClient) Get(arg0 context.Context, arg1, arg2 string) (operationalinsights.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(operationalinsights.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockWorkspacesClientMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkspacesClient)(nil).Get), arg0, arg1, arg2)
}

// GetSharedKeys mocks base method
func (m *MockWorkspacesClient) GetSharedKeys(arg0 context.Context, arg1, arg2 string) (operationalinsights.SharedKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedKeys", arg0, arg1, arg2)
	ret0, _ := ret[0].(operationalinsights.SharedKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharedKeys indicates an expected call of GetSharedKeys
func (mr *MockWorkspacesClientMockRecorder) GetSharedKeys(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedKeys", reflect.TypeOf((*MockWorkspacesClient)(nil).GetSharedKeys), arg0, arg1, arg2)
}
