#!/bin/bash -e

export AZURE_TENANT_ID="$AZURE_ROOT_TENANT_ID"
export AZURE_SUBSCRIPTION_ID="$AZURE_ROOT_SUBSCRIPTION_ID"
export AZURE_CLIENT_ID="$AZURE_ROOT_CLIENT_ID"
export AZURE_CLIENT_SECRET="$AZURE_ROOT_CLIENT_SECRET"

go run main.go
