// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/openshift-azure/pkg/cluster/kubeclient (interfaces: Kubeclient)

// Package mock_kubeclient is a generated GoMock package.
package mock_kubeclient

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockKubeclient is a mock of Kubeclient interface
type MockKubeclient struct {
	ctrl     *gomock.Controller
	recorder *MockKubeclientMockRecorder
}

// MockKubeclientMockRecorder is the mock recorder for MockKubeclient
type MockKubeclientMockRecorder struct {
	mock *MockKubeclient
}

// NewMockKubeclient creates a new mock instance
func NewMockKubeclient(ctrl *gomock.Controller) *MockKubeclient {
	mock := &MockKubeclient{ctrl: ctrl}
	mock.recorder = &MockKubeclientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKubeclient) EXPECT() *MockKubeclientMockRecorder {
	return m.recorder
}

// BackupCluster mocks base method
func (m *MockKubeclient) BackupCluster(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupCluster", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackupCluster indicates an expected call of BackupCluster
func (mr *MockKubeclientMockRecorder) BackupCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupCluster", reflect.TypeOf((*MockKubeclient)(nil).BackupCluster), arg0, arg1)
}

// DeleteMaster mocks base method
func (m *MockKubeclient) DeleteMaster(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaster", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaster indicates an expected call of DeleteMaster
func (mr *MockKubeclientMockRecorder) DeleteMaster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaster", reflect.TypeOf((*MockKubeclient)(nil).DeleteMaster), arg0)
}

// DeletePod mocks base method
func (m *MockKubeclient) DeletePod(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePod", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePod indicates an expected call of DeletePod
func (mr *MockKubeclientMockRecorder) DeletePod(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePod", reflect.TypeOf((*MockKubeclient)(nil).DeletePod), arg0, arg1, arg2)
}

// DrainAndDeleteWorker mocks base method
func (m *MockKubeclient) DrainAndDeleteWorker(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainAndDeleteWorker", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DrainAndDeleteWorker indicates an expected call of DrainAndDeleteWorker
func (mr *MockKubeclientMockRecorder) DrainAndDeleteWorker(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainAndDeleteWorker", reflect.TypeOf((*MockKubeclient)(nil).DrainAndDeleteWorker), arg0, arg1)
}

// GetControlPlanePods mocks base method
func (m *MockKubeclient) GetControlPlanePods(arg0 context.Context) ([]v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControlPlanePods", arg0)
	ret0, _ := ret[0].([]v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetControlPlanePods indicates an expected call of GetControlPlanePods
func (mr *MockKubeclientMockRecorder) GetControlPlanePods(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControlPlanePods", reflect.TypeOf((*MockKubeclient)(nil).GetControlPlanePods), arg0)
}

// WaitForReadyMaster mocks base method
func (m *MockKubeclient) WaitForReadyMaster(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForReadyMaster", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForReadyMaster indicates an expected call of WaitForReadyMaster
func (mr *MockKubeclientMockRecorder) WaitForReadyMaster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForReadyMaster", reflect.TypeOf((*MockKubeclient)(nil).WaitForReadyMaster), arg0, arg1)
}

// WaitForReadySyncPod mocks base method
func (m *MockKubeclient) WaitForReadySyncPod(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForReadySyncPod", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForReadySyncPod indicates an expected call of WaitForReadySyncPod
func (mr *MockKubeclientMockRecorder) WaitForReadySyncPod(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForReadySyncPod", reflect.TypeOf((*MockKubeclient)(nil).WaitForReadySyncPod), arg0)
}

// WaitForReadyWorker mocks base method
func (m *MockKubeclient) WaitForReadyWorker(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForReadyWorker", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForReadyWorker indicates an expected call of WaitForReadyWorker
func (mr *MockKubeclientMockRecorder) WaitForReadyWorker(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForReadyWorker", reflect.TypeOf((*MockKubeclient)(nil).WaitForReadyWorker), arg0, arg1)
}
