// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package mock_cluster is a generated GoMock package.
package mock_cluster

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	api "github.com/openshift/openshift-azure/pkg/api"
)

// MockUpgrader is a mock of Upgrader interface
type MockUpgrader struct {
	ctrl     *gomock.Controller
	recorder *MockUpgraderMockRecorder
}

// MockUpgraderMockRecorder is the mock recorder for MockUpgrader
type MockUpgraderMockRecorder struct {
	mock *MockUpgrader
}

// NewMockUpgrader creates a new mock instance
func NewMockUpgrader(ctrl *gomock.Controller) *MockUpgrader {
	mock := &MockUpgrader{ctrl: ctrl}
	mock.recorder = &MockUpgraderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUpgrader) EXPECT() *MockUpgraderMockRecorder {
	return m.recorder
}

// CreateClients mocks base method
func (m *MockUpgrader) CreateClients(ctx context.Context, cs *api.OpenShiftManagedCluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClients", ctx, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClients indicates an expected call of CreateClients
func (mr *MockUpgraderMockRecorder) CreateClients(ctx, cs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClients", reflect.TypeOf((*MockUpgrader)(nil).CreateClients), ctx, cs)
}

// Deploy mocks base method
func (m *MockUpgrader) Deploy(ctx context.Context, cs *api.OpenShiftManagedCluster, azuretemplate map[string]interface{}, deployFn api.DeployFn, suffix string) *api.PluginError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctx, cs, azuretemplate, deployFn, suffix)
	ret0, _ := ret[0].(*api.PluginError)
	return ret0
}

// Deploy indicates an expected call of Deploy
func (mr *MockUpgraderMockRecorder) Deploy(ctx, cs, azuretemplate, deployFn, suffix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockUpgrader)(nil).Deploy), ctx, cs, azuretemplate, deployFn, suffix)
}

// Update mocks base method
func (m *MockUpgrader) Update(ctx context.Context, cs *api.OpenShiftManagedCluster, azuretemplate map[string]interface{}, deployFn api.DeployFn, suffix string) *api.PluginError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cs, azuretemplate, deployFn, suffix)
	ret0, _ := ret[0].(*api.PluginError)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockUpgraderMockRecorder) Update(ctx, cs, azuretemplate, deployFn, suffix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpgrader)(nil).Update), ctx, cs, azuretemplate, deployFn, suffix)
}

// EtcdRestore mocks base method
func (m *MockUpgrader) EtcdRestore(ctx context.Context, cs *api.OpenShiftManagedCluster, azuretemplate map[string]interface{}, deployFn api.DeployFn) *api.PluginError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EtcdRestore", ctx, cs, azuretemplate, deployFn)
	ret0, _ := ret[0].(*api.PluginError)
	return ret0
}

// EtcdRestore indicates an expected call of EtcdRestore
func (mr *MockUpgraderMockRecorder) EtcdRestore(ctx, cs, azuretemplate, deployFn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EtcdRestore", reflect.TypeOf((*MockUpgrader)(nil).EtcdRestore), ctx, cs, azuretemplate, deployFn)
}

// HealthCheck mocks base method
func (m *MockUpgrader) HealthCheck(ctx context.Context, cs *api.OpenShiftManagedCluster) *api.PluginError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx, cs)
	ret0, _ := ret[0].(*api.PluginError)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck
func (mr *MockUpgraderMockRecorder) HealthCheck(ctx, cs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockUpgrader)(nil).HealthCheck), ctx, cs)
}

// WaitForInfraServices mocks base method
func (m *MockUpgrader) WaitForInfraServices(ctx context.Context, cs *api.OpenShiftManagedCluster) *api.PluginError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForInfraServices", ctx, cs)
	ret0, _ := ret[0].(*api.PluginError)
	return ret0
}

// WaitForInfraServices indicates an expected call of WaitForInfraServices
func (mr *MockUpgraderMockRecorder) WaitForInfraServices(ctx, cs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForInfraServices", reflect.TypeOf((*MockUpgrader)(nil).WaitForInfraServices), ctx, cs)
}
